name: Testing CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Conda Envs
      uses: actions/cache@v2
      with:
        path: |
          ~/miniconda3
          build/*.txt
        key: ${{ runner.OS }}-conda-env-cache-${{ hashFiles('requirements/*.txt', 'setup.py', 'makefile*') }}

    - name: make conda
      run: make conda

    - name: make lint
      run: make lint
    - name: make mypy
      run: make mypy
    - name: make test
      run: make test

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Conda Envs
      uses: actions/cache@v2
      with:
        path: |
          ~/miniconda3
          build/*.txt
        key: ${{ runner.OS }}-conda-env-cache-${{ hashFiles('requirements/*.txt', 'setup.py', 'makefile*') }}

    - name: make conda
      run: make conda

    - name: debug make fmt
      run: make fmt
    - name: debug diff
      run: git diff

    - name: make lint
      run: make lint || true
    - name: make mypy
      run: make mypy || true
    - name: make test
      run: make test || true
